// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX7poQz1aaW_Ym5XWo73bbg4tptoyWYYY',
    appId: '1:500166087872:web:0c998e48ccf49d3e6b0925',
    messagingSenderId: '500166087872',
    projectId: 'emergency-cb8cd',
    authDomain: 'emergency-cb8cd.firebaseapp.com',
    storageBucket: 'emergency-cb8cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHclLBMD8FysHKk_QAb-nE3K92zl4hs7Q',
    appId: '1:500166087872:android:6ecb5753127395266b0925',
    messagingSenderId: '500166087872',
    projectId: 'emergency-cb8cd',
    storageBucket: 'emergency-cb8cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdWDIL2uJGkVOl4Wc8ccYt5ndyvkyqAC0',
    appId: '1:500166087872:ios:df43ce0169c98bdb6b0925',
    messagingSenderId: '500166087872',
    projectId: 'emergency-cb8cd',
    storageBucket: 'emergency-cb8cd.firebasestorage.app',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdWDIL2uJGkVOl4Wc8ccYt5ndyvkyqAC0',
    appId: '1:500166087872:ios:df43ce0169c98bdb6b0925',
    messagingSenderId: '500166087872',
    projectId: 'emergency-cb8cd',
    storageBucket: 'emergency-cb8cd.firebasestorage.app',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX7poQz1aaW_Ym5XWo73bbg4tptoyWYYY',
    appId: '1:500166087872:web:6cc2735d6f22bce36b0925',
    messagingSenderId: '500166087872',
    projectId: 'emergency-cb8cd',
    authDomain: 'emergency-cb8cd.firebaseapp.com',
    storageBucket: 'emergency-cb8cd.firebasestorage.app',
  );
}
